- name: "update yum packages."
  become: true
  yum:
    update_cache: true
- name: "upgrade packages"
  become: true
  yum:
    name: "*"
    state: latest
- name: "install node dependencies"
  become: true
  shell: |
    curl –sL https://rpm.nodesource.com/setup_10.x | sudo bash -
- name: "install nodejs"
  become: yes
  yum:
    name: "nodejs"
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present
- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'
- name: "copy files"
  copy:
    src: index.js
    dest: ~/web
    backup: true
- name: "start server"
  shell: pm2 start ~/web/index.js -f
